// This file is similar to the auto-generated entry point, except that it does not include support
// for Microsoft.Testing.Platform (which is unnecessary for our acceptance tests)

[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public class XunitAutoGeneratedEntryPoint
{
	public static int Main(string[] args)
	{
		return global::Xunit.Runner.InProc.SystemConsole.ConsoleRunner.Run(args).GetAwaiter().GetResult();
	}
}
